l=["Apple","Mango","Strawberry","Watermelon","Guva"]
print("lenght of list ",len(l))
print("first element ",l[0])
print("last element ",l[-1])
l.append("Banana")
print("updated list",l)
l.remove("Mango")
print("updated list",l)
l.sort()
print("updated list",l)
l.reverse()
print("updated list",l)